### ISSUE TITLE
Unable to upload code after update to 2.3.2 (invalid value '460800' for option 'UploadSpeed')

### ISSUE THREAD

**Issue by wangzongming** [arduino/arduino-ide#2450]
### Describe the problem

Hello, I have a problem and I can't find a solution.

After installing the latest IDE version, upload nodemcu-32s to alert the following error

```
nvalid FQBN: getting build properties for board esp32:esp32:nodemcu-32s: invalid value '460800' for option 'UploadSpeed'

Compilation error: Invalid FQBN: getting build properties for board esp32:esp32:nodemcu-32s: invalid value '460800' for option 'UploadSpeed'
```

### To reproduce

computer：windos11
Arduino IDE 2.3.2
esp32 board 3.0.1

### Expected behavior

Can upload the code normally

### Arduino IDE version

Arduino IDE 2.3.2

### Operating system

Windows

### Operating system version

window 11

### Additional context

I used the old version of ide is able to upload normally, today after the upgrade is broken.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by wangzongming** [comment]
https://github.com/espressif/arduino-esp32/issues/9786
