### ISSUE TITLE
arduinoFFT.h  not working with ide2.3.2

### ISSUE THREAD

**Issue by Juan-Acevedo** [arduino/arduino-ide#2455]
### Describe the problem

```text
C:\Users\Juan Acevedo\Documents\Arduino\ESP32_Restart_TFT_32_Bands_Mono_ASA\ESP32_Restart_TFT_32_Bands_Mono_ASA.ino:26:1: error: 'arduinoFFT' does not name a type; did you mean 'ArduinoFFT'?
   26 | arduinoFFT FFT = arduinoFFT();
      | ^~~~~~~~~~
      | ArduinoFFT
C:\Users\Juan Acevedo\Documents\Arduino\ESP32_Restart_TFT_32_Bands_Mono_ASA\ESP32_Restart_TFT_32_Bands_Mono_ASA.ino: In function 'void loop()':
C:\Users\Juan Acevedo\Documents\Arduino\ESP32_Restart_TFT_32_Bands_Mono_ASA\ESP32_Restart_TFT_32_Bands_Mono_ASA.ino:286:5: error: 'FFT' was not declared in this scope
  286 |     FFT.DCRemoval();
      |     ^~~

exit status 1

Compilation error: 'arduinoFFT' does not name a type; did you mean 'ArduinoFFT'?
```

### To reproduce

Take any code using `<arduinoFFT.h>` and try to compile using ide2.3.2

### Expected behavior

You expect the code to compile.

### Arduino IDE version

ide2.3.2

### Operating system

Windows

### Operating system version

11

### Additional context

The code was working with the previous ide version. Now it does not compile.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details

**Comment by per1234** [comment]
Hi @Juan-Acevedo. Thanks for your interest in this open source project. This issue tracker is only to be used to report bugs or feature requests specific to the project. This topic is more appropriate for the Arduino Forum. I'm sure we will be able to help you out over there:

https://forum.arduino.cc/
