### ISSUE TITLE
SSL root certificate upload fails: "Error during firmware flashing: missing board address"

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#2179]
### Describe the problem

Arduino IDE includes [a tool for uploading SSL root certificates](https://docs.arduino.cc/software/ide-v2/tutorials/ide-v2-fw-cert-uploader#certificates-uploader) to the network connectivity module of certain Arduino boards.

🐛 A spurious failure occurs whenever attempting to use the tool.

#### Equipment

One of the boards supported by the "**Upload SSL Root Certificates**" feature:

- [**UNO R4 WiFi**](https://docs.arduino.cc/hardware/uno-r4-wifi)
- [**Nano 33 IoT**](https://docs.arduino.cc/hardware/nano-33-iot)
- [**MKR WiFi 1010**](https://docs.arduino.cc/hardware/mkr-wifi-1010)
- [**MKR 1000 WiFi**](https://docs.arduino.cc/hardware/mkr-1000-wifi)
- [**Nano RP2040 Connect**](https://docs.arduino.cc/hardware/nano-rp2040-connect)
- [**Uno WiFi Rev2**](https://docs.arduino.cc/hardware/uno-wifi-rev2)

#### Steps

1. Connect the certificate upload target board to your computer with a USB cable if it is not already.
1. Select **Tools > Upload SSL Root Certificates** from the Arduino IDE menus.
1. Check the box to the right of "**arduino.cc:443**" in the "**1. Select certificate to upload**" field.
1. Select the board from the "**2. Select destination board and upload certificate**" menu.
1. Click the "**UPLOAD**" button.

🐛 The process fails unexpectedly:

> **⚠ Upload failed. Please try again.**

If you check the logs, you see it was caused by an "`Error during firmware flashing: missing board address`" error:

```text
2023-08-19T21:25:17.060Z fwuploader ERROR Error: Error executing C:\arduino-tools\214-69ae38e\resources\app\lib\backend\resources\arduino-fwuploader.exe certificates flash -b arduino:samd:nano_33_iot -a COM5 -u arduino.cc:443: Error during firmware flashing: missing board address
    at ChildProcess.<anonymous> (C:\arduino-tools\214-69ae38e\resources\app\lib\backend\main.js:2:603367)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
2023-08-19T21:25:17.060Z root ERROR Request uploadCertificates failed with error: Error executing C:\arduino-tools\214-69ae38e\resources\app\lib\backend\resources\arduino-fwuploader.exe certificates flash -b arduino:samd:nano_33_iot -a COM5 -u arduino.cc:443: Error during firmware flashing: missing board address Error: Error executing C:\arduino-tools\214-69ae38e\resources\app\lib\backend\resources\arduino-fwuploader.exe certificates flash -b arduino:samd:nano_33_iot -a COM5 -u arduino.cc:443: Error during firmware flashing: missing board address
    at ChildProcess.<anonymous> (C:\arduino-tools\214-69ae38e\resources\app\lib\backend\main.js:2:603367)
    at ChildProcess.emit (node:events:513:28)
    at ChildProcess._handle.onexit (node:internal/child_process:291:12)
```

### Expected behavior

"**Upload SSL Root Certificates**" tool is functional.

### Arduino IDE version

69ae38e

### Operating system

Windows

### Operating system version

11

### Additional context

I bisected the regression to 9d2297c (does not occur when using the build for the previous commit e47fb2e).

I see that an array of arguments is used for the [`arduino-fwuploader firmware`](https://arduino.github.io/arduino-fwuploader/dev/commands/arduino-fwuploader_firmware/) invocations, which did not experience a regression:

https://github.com/arduino/arduino-ide/blob/5a76be306a125a7fccd32a092646bbd7aabfaaa3/arduino-ide-extension/src/node/arduino-firmware-uploader-impl.ts#L57-L66

while the flag arguments are passed as a string in the `arduino-fwuploader certificates flash` invocation:

https://github.com/arduino/arduino-ide/blob/5a76be306a125a7fccd32a092646bbd7aabfaaa3/arduino-ide-extension/src/browser/contributions/upload-certificate.ts#L78-L82

---

Confusingly, the command line shown in the error message in the logs does correctly contain the [`-a` address flag](https://arduino.github.io/arduino-fwuploader/dev/commands/arduino-fwuploader_certificates_flash/#options) it claims is missing:

```text
C:\arduino-tools\214-69ae38e\resources\app\lib\backend\resources\arduino-fwuploader.exe certificates flash -b arduino:samd:nano_33_iot -a COM5 -u arduino.cc:443
```

You can produce the "`Error during firmware flashing: missing board address`" error when invoking the command directly by wrapping the set of flags in a single set of quotes:

```text
$ "C:\arduino-tools\214-69ae38e\resources\app\lib\backend\resources\arduino-fwuploader.exe" certificates flash "-b arduino:samd:nano_33_iot -a COM5 -u arduino.cc:443"
Error during firmware flashing: missing board address
```

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/arduino-ide/issues?q=)
- [X] I verified the problem still occurs when using the latest [nightly build](https://www.arduino.cc/en/software#nightly-builds)
- [X] My report contains all necessary details
