### ISSUE TITLE
Saved code is shown in compilation error messages even when compiling dirty sketch

### ISSUE THREAD

**Issue by per1234** [arduino/arduino-ide#12]
**Describe the bug**
When compiling a sketch with unsaved changes, the code in the editor is compiled (good), but the code from the saved version of the sketch is used in the error message when there is a compilation failure (bad).

**To Reproduce**
1. **File > Preferences**
2. Uncheck the box next to "Auto save".
3. Click the "OK" button.
4. Open a sketch that will compile without errors (e.g., **File > New**).
4. Make changes to the sketch code that would cause a compilation failure. Don't save.
5. **Sketch > Verify/Compile**. The compilation fails.
6. Check the error message in the output menu. The quoted line of code is from the saved version of the sketch, not the code that caused the error.

For example, if I have this sketch saved:
```c++
void setup() {}
void loop() {}
```
and this is the dirty version:
```c++
foovoid setup() {}
void loop() {}
```

The compilation error:
```
c:\Users\per\AppData\Local\Temp\.arduinoIDE-unsaved2021112-12840-1u0f2iv.mccj\sketch_feb12a\sketch_feb12a.ino:1:1: error: 'foovoid' does not name a type; did you mean 'void'?
 void setup() {}
 ^~~~~~~
 void
c:\Users\per\AppData\Local\Temp\.arduinoIDE-unsaved2021112-12840-1u0f2iv.mccj\sketch_feb12a\sketch_feb12a.ino:1:1: error: 'foovoid' does not name a type; did you mean 'void'?
 void setup() {}
 ^~~~~~~
 void
Compilation error: Error: 2 UNKNOWN: exit status 1
```
**Expected behavior**
The code of the sketch that was compiled should be shown in the error output:
```
c:\Users\per\AppData\Local\Temp\.arduinoIDE-unsaved2021112-12840-1u0f2iv.mccj\sketch_feb12a\sketch_feb12a.ino:1:1: error: 'foovoid' does not name a type; did you mean 'void'?
 foovoid setup() {}
 ^~~~~~~
Compilation error: Error: 2 UNKNOWN: exit status 1
```
**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version: 2.0.0-beta.1-snapshot.9e35571
Date: 2021-02-12T08:28:48.914Z
CLI Version: nightly-20210212 alpha [560025a6]

**Additional context**

The compilation of the dirty sketch is a new behavior introduced by https://github.com/arduino/arduino-ide/pull/9/commits/f53013b4a3c23670f4e90a1dda86fffbab64a78c as a fix for https://github.com/arduino/arduino-pro-ide/issues/432
